module.exports = {
  REGISTRATION_ERROR: "Registration error!",
  REGISTRATION_FAILED: "Registration failed!",
  REGISTRATION_SUCCESS: "User registrartion successfull",
  LOGIN_SUCCESS: "Login successsfull",
  LOGIN_FAILED: "Login successsfull",
  USER_NOT_FOUND: "User not Found",
  WRONG_PASSWORD: "Password is invalid!",
  TOKEN_EXPIRED: "Token Expired!",
  USER_EXIST: "User already exist",
  PROFILE_ERROR: "Profile error",
  USER_PROFILE: "User profile is ",
  DELETE_SUCCSESS: "User deleted",
  DELETE_ERROR: "Delete error!",
  LOGOUT_SUCCESS: "LogOut successful",
  LOGOUT_ERROR: "Logout error!",
  UPLOAD_MULTER_ERROR: "Upload failed due to multer error!",
  UPLOAD_ERROR: "Upload failed due to unknown error!",
  UOLOAD_MESSAGE: " No file uploaded!",
  UPLOAD_VALIDATION: "Only JPEG, PNG, and PDF files are allowed!",
  UPLOAD_LIMIT: "File size exceeds 5MB limit!",
  UPLOAD_SUCCESS: "Files uploaded successfully",
  ADDRESS_ADDED: "Address added successfully",
  ADDRESS_ERROR: "Address not added!",
  ADMIN_EXIST: "Admin already exists1",
  EMAIL_USE: "Email already in use!",
  FAILED_FETCH: "Failed to fetch user!",
  INVALID_HEADERS: "Invalid or missing User ID in headers!",
  INVALID_ID: "Invalid or missing User ID!",
  ID_REQUIRED: "User ID and Address ID are required!",
  ADSRESS_NOT_FOUND: "Address not found for this user!",
  PRIMERY_ADSRESS_UPDATED: "Primary Address Updated Successfully",
  PRIMERY_ADSRESS_NOT_FOUND: "No primary address found!",
  REFRESH_TOKEN_MISSING: "Refresh token missing!",
  ACCESS_TOKEN_REFRESHED: "Access token refreshed",
  REFRESH_TOKEN_EXPIRE: "Refresh token expired, please login again!",
  INVALID_REFRESH_TOKEN: "Invalid refresh token!",
  TOKEN_NOT_PROVIDED: "Token not provided!",
  INVALID_TOKEN_IN_REDISH: "Invalid or expired token in Redis!",
  INVALID_TOKEN: "Invalid or expired token!",

  // DATABASE
  DATABASE_CONNECT: "Database is connected",
  SERVER_RUNNING: "Server is running on",
  SERVER_ERROR: "Server error!",

  // REDIS

  REDIS_CONNECT: "Connected to Redis",
  REDIS_CLIENT_ERROR: "'Redis Client Error !'",
  REDIS_FAILED: "Failed to connect to Redis !",

  // NOT AUTHORIZED

  USER_NOT_AUTHORIZED: "You are not Authurized as User !",
  ADMIN_NOT_AUTHORIZED: "You are not Authurized as Admin !",
  USER_ALREADY_DELETED: "User is already deleted and cannot be modified.",
  STATUS_UPDATED: "User status updated successfully.",
  USER_ADMIN_DELETED:
    "Your account has been deleted by Admin. Please contact support.",
  FETCH_SUCCESS: "Fetch successfully",

  //PASSWORD MACHANISM
  OTP_SENT_SUCCESS: "OTP sent successfully",
  OTP_SEND_FAILED: "OTP send failed",
  PASSWORD_MISMATCH: "New password and Confirm password do not match!",
  PASSWORD_MATCH: "New password should not be same as Old password",
  OTP_NOT_VERFIFIED: " Otp not verified",
  OTP_VERIFIED: "Youre OTP is verified",
  INCORRECT_OLD_PASSWORD: "Old password is incorrect",
  PAASWORD_RESET_SUCCESS: "Password reset successfully",
  PASSWORD_RESET_FAILED: "Password reset failed",
  INVALID_OTP: "Otp invalid ",
  OTP_EXPIRED: " Youre OTP is Expired ",
};
